### ISSUE TITLE
Customer Reported Bug

### ISSUE THREAD

**Issue by robertclaus** [TodePond/DreamBerd#600]
**edit** added the stack trace

Our company uses DreamBerd in our enterprise SAAS offering and a customer reported a bug back in January. Our intern wasn't able to figure out the cause and my manager said it's probably just a bug in DreamBerd. Can you fix it for us?

Here's the stack trace:

<code>

**Error Report**

**Timestamp:** 2024-03-11 09:06:42 CDT

**Exception Type:** System.NullReferenceException

**Message:** Object reference not set to an instance of an object.

**Stack Trace:**

  at MyApplication.ProductController.GetDetails(Int32 id) in C:\Users\Public\Source\MyApp\ProductController.cs:line 112
  at MyApplication.ProductListView.OnProductSelectionChanged(Object sender, EventArgs e) in C:\Users\Public\Source\MyApp\ProductListView.cs:line 48
  at System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.Control.WmMouseDown(Message& m) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.Control.WndProc(Message& m) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.ScrollableControl.WndProc(Message& m) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.ListView.WndProc(Message& m) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.Control.ControlNativeWindowProc(Message& m) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.SafeMessageWindowManager.DefWndProc(HandleRef hWnd, WM msg, IntPtr wParam, IntPtr lParam) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wParam, IntPtr lParam) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.Application.WndProc(WmMessage msg, IntPtr wParam, IntPtr lParam) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.Message.Win32WndProc(WndProcCallback proc, IntPtr wParam, IntPtr lParam) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.Message.Dispatch(IntPtr hwndPtr, WM msg, IntPtr wParam, IntPtr lParam) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Windows.Forms.Application.ComponentManager.SystemLoop(Object o) in C:\Windows\System32\...\System.Windows.Forms.dll:line xxxx
  at System.Threading.ThreadHelper.ThreadStart() in C:\Windows\System32\...\mscorlib.dll:line xxxx

**Inner Exception:**

**---**

**Additional Information:**

The error seems to have originated from trying to access a null object reference in the `GetDetails` method of the `ProductController` class. This might be due to invalid data being passed to the method or an issue with how the object is being retrieved.
</code>

**Comment by jackbridger** [comment]
we've also built our business on dreamberd and have the same error
our team is launching dreamberd's new features this week to celebrate us hitting $1bn revenue, any chance this bug could be fixed by tomorrow close of business?
